# Generated by Django 3.2 on 2021-04-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField()),
                ('oxigenacion', models.IntegerField()),
                ('positivo', models.BooleanField()),
            ],
        ),
    ]
